sudo: false

# Use Maven
language: java

jobs:
 include:
  - stage: build
    script: "mvn clean install"
  - stage: release
    script: "mvn scm:tag -Dtag=$(mvn -q -Dexec.executable=\"echo\" -Dexec.args='${project.version}' --non-recursive org.codehaus.mojo:exec-maven-plugin:1.3.1:exec 2> /dev/null)"
    if: (branch = master)
