sudo: false

# Use Maven
language: java

script:
# - env
# - git checkout $TRAVIS_BRANCH
# - git branch
 - mvn clean install
 - echo $(mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive org.codehaus.mojo:exec-maven-plugin:1.3.1:exec 2> /dev/null)

